Prefix: '&c[&8Lockdown&c]&f'
# Lockdown Notify Type Tells The Plugin What Players If Any To Announce The Lockdown To
# 0 - All Players Online
# 1 - Only Players With hllockdown.lockdown.notify (Great For Staff)
# 2 - No One
Lockdown-Notify-Type: 0
Messages:
  Unknown-Command: '&cUnknown Command!'
  No-Permission: "&cYou don't have permission to do this!"
  Reloaded-Message: '&2Config File Reloaded'
  Lockdown-Message: 'The Server Is Under Lockdown, Try Again Later'
  Lockdown-Confirm-Message: 'Server {status}'
  Lockdown-Notify-Message: '{sender} {status} The Server'
