name: ${project.name}
version: ${project.version}
author: Haileykins
description: Simple Server Security In One Command
main: me.haileykins.hllockdown.HLLockdown

commands:
  bouncer:
    description: Main Command
  lockdown:
    description: Locks Down The Server